{
 "title": "Kubernetes Cluster RAM and CPU Utilization",
 "description": "Cluster RAM and CPU utilization grouped by namespaces, deployments and specific pods. This dashboard shows the values at specific point in time, its useful for get an instant feeling about what takes most of the resources in the cluster.",
 "tags": [
  "kubernetes",
  "utilization",
  "ram",
  "cpu"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "The memory usage in percentage of all nodes in the cluster.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (kube_node_status_capacity{resource=\"memory\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "The average CPU usage of all the nodes in the cluster.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[5m])) / sum (kube_node_status_capacity{resource=\"cpu\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by deployment",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes deployment",
   "gridPos": { "h": 13, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (container, namespace) (container_memory_working_set_bytes{container!=\"POD\", container!=\"\"}))",
     "legendFormat": "{{ namespace }} - {{ container}}"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes pod",
   "gridPos": { "h": 13, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod, namespace) (container_memory_working_set_bytes{pod!=\"\",container!=\"POD\", container!=\"\"}))",
     "legendFormat": "{{ namespace }} - {{ pod}}"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "description": "Total number of cores on k8s cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "This is the sum of CPU request - All namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory usage by namespace",
   "type": "bargauge",
   "description": "The memory usage in a cluster grouped by Kubernetes namespace",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (container_memory_working_set_bytes{pod!=\"\",container!=\"POD\", container!=\"\"}))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "stat",
   "description": "Total number of used cores",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Total memory allocated on k8s cluster",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "Total Mem."
    }
   ]
  },
  {
   "title": "Mem Request",
   "type": "stat",
   "description": "Total memory request - All namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Usage by deployment",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes deployment",
   "gridPos": { "h": 13, "w": 7, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (container, namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])))",
     "legendFormat": "{{ namespace }} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage by pod",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes pod",
   "gridPos": { "h": 13, "w": 7, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod, namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])))",
     "legendFormat": "{{ namespace }} - {{ pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by namespace",
   "type": "bargauge",
   "description": "The CPU usage in a cluster grouped by Kubernetes namespace",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Used Mem.",
   "type": "stat",
   "description": "Total used memory",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  }
 ]
}