{
 "title": "JMX Exporter (Java Services)",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus",
  "JMX"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values({job=\"java-services\"},job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Committed Heap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Heap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Logical Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"} * 100",
     "legendFormat": "SystemCpuLoad"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"} * 100",
     "legendFormat": "ProcessCpuLoad"
    }
   ]
  },
  { "title": "JVM Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Eden Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Eden Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Eden Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Old Gen\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Old Gen\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Old Gen\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Survivor Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Survivor Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used  {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"G1 Survivor Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed  {{pod_name}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_max{pool=~\"CodeHeap '.*nmethods'\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Max {{pod_name}}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{pool=~\"CodeHeap '.*nmethods'\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Used {{pod_name}}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{pool=~\"CodeHeap '.*nmethods'\",job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Committed {{pod_name}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM current threads  {{pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM daemon threads {{pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked{job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads  {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{gc}}  {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"$job\",namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "{{gc}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "loaded  {{pod_name}}"
    },
    {
     "expr": "java_lang_ClassLoading_UnloadedClassCount{job=~\"$job\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "un-loaded"
    }
   ]
  }
 ]
}