{
 "title": "Kafka-zookeeper Dashboard",
 "tags": [ "5.4.2" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Kafka Consumer Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer Group Lag",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum(kafka_consumergroup_lag_sum) by (consumergroup, topic))",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Consumption Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum(delta(kafka_consumergroup_current_offset[10m])) by (consumergroup, topic))",
     "legendFormat": "{{Lag}}"
    }
   ]
  },
  { "title": "Confluent Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cp_kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_activecontrollercount)"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_controllerstats_uncleanleaderelectionspersec)"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Aggregated Kafka Broker Pods CPU Usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"kafka-v2-0|kafka-v2-1|kafka-v2-2\"}[5m])) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"kafka-v2-(\\\\d+)\"}) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"kafka-data-kafka-v2.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesinpersec)",
     "legendFormat": "Incoming Byte Rate"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_bytesoutpersec)",
     "legendFormat": "Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec)",
     "legendFormat": "{{Messages In Per Second}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalproducerequestspersec)",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedproducerequestspersec)",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_totalfetchrequestspersec)",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_failedfetchrequestspersec)",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_network_socketserver_networkprocessoravgidlepercent*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "description": "Request Handler Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_kafkarequesthandlerpool_requesthandleravgidlepercent*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum Size",
     "type": "stat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(cp_zookeeper_quorumsize)" }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "stat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_zookeeper_numaliveconnections)"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cp_zookeeper_outstandingrequests",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(cp_zookeeper_inmemorydatatree_nodecount)"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "stat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cp_zookeeper_inmemorydatatree_watchcount)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"zookeeper-v2-0|zookeeper-v2-1|zookeeper-v2-2\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"zookeeper-v2-(\\\\d+)\"}) by (pod)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"zookeeper-data-zookeeper-v2.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cp_zookeeper_minrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cp_zookeeper_avgrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cp_zookeeper_maxrequestlatency", "legendFormat": "{{kubernetes_pod_name}}" }
     ]
    }
   ]
  }
 ]
}