{
 "title": "1 Kubernetes cluster overview(कुबरनेटेस)",
 "description": "This dashboard can help troubleshooting issue in k8s cluster at cluster, node and namespace level.",
 "tags": [
  "kubernetes",
  "k8s",
  "namespace"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_created,node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(kube_namespace_labels)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "kube_pod_container_info{namespace=\"$namespace\"}"
    }
   },
   {
    "name": "duration",
    "query": "10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster age",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(time() - kube_service_created{namespace=\"default\",service=\"kubernetes\"})"
      }
     ]
    },
    {
     "title": "Namespaces ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "Total pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Waiting pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Terminated pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "burstable  pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Besteffort  pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "PVCs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "cluster  node details",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "targets": [
      { "expr": "kube_node_info", "legendFormat": "{{node}}" },
      {
       "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
      },
      {
       "expr": "((label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))  -  (label_replace((node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))) /  (label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\")) "
      },
      {
       "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
      },
      {
       "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
      },
      { "expr": "kube_node_role" }
     ]
    },
    {
     "title": "Memory usage by namespace in cluster",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (namespace)(container_memory_usage_bytes{pod!=\"POD\",namespace!=\"\"}))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Pod startup latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": " histogram_quantile(0.99,\n  sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\"}[10m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}",
       "legendFormat": "{{node}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Consumer Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Group Lag",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sort_desc(sum(kafka_consumergroup_lag_sum) by (consumergroup, topic))",
       "legendFormat": "Lag"
      }
     ]
    },
    {
     "title": "Consumption Rate",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sort_desc(sum(delta(kafka_consumergroup_current_offset[10m])) by (consumergroup, topic))",
       "legendFormat": "Lag"
      }
     ]
    },
    {
     "title": "Dead Letters",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sort_desc(sum(kafka_topic_partition_current_offset{topic=~\".*deadletter\"}) by (topic))",
       "legendFormat": "Lag"
      }
     ]
    },
    {
     "title": "Message Consumption",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_current_offset)  by (consumergroup, topic)",
       "legendFormat": "{{consumergroup}} (topic: {{topic}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVCs available capacity in namespacee $namespace",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=\"$namespace\"}\n  / kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=\"$namespace\"}\n ",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "persistentvolumeclaim status in namespace $namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(kube_persistentvolumeclaim_access_mode{namespace=\"$namespace\"})",
       "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\",phase=\"Bound\"}",
       "legendFormat": "Bound::{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "PVCs Failed",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Failed\",namespace=\"$namespace\"} != 0) "
      }
     ]
    },
    {
     "title": "PVCs Pending",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolume_status_phase{job=\"kube-state-metrics\",phase=\"Pending\",namespace=\"$namespace\"} != 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace $namespace details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployments",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_created{namespace=\"$namespace\"})",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Ready pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_ready{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Terminated pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_terminated{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Waiting pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting{namespace=\"$namespace\"} !=0 ) or vector(0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Guaranteed  pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\",id!~\".*.burstable.*|.*.besteffort.*\",id!~\".*.scope\",pod!=\"\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "total  pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{namespace=\"$namespace\",container=\"POD\"}))"
      }
     ]
    },
    {
     "title": "Besteffort  pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "burstable  pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\",namespace=\"$namespace\",container=\"POD\"}))"
      }
     ]
    },
    {
     "title": "pods running in $namespace",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{namespace=\"$namespace\"}"
      },
      {
       "expr": "sum\r\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "Memory usage"
      },
      {
       "expr": "kube_pod_info{namespace=\"$namespace\"}"
      },
      {
       "expr": "sum by(pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\"})"
      },
      {
       "expr": "quantile_over_time(0.95,\r\n  sum by (pod) (\r\n    rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container_name!=\"POD\"}[10m])\r\n  )[2d:]\r\n)",
       "legendFormat": "CPU Usage [95th Percentile]"
      }
     ]
    },
    {
     "title": "Total CPU usage in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": " CPU usage by pod in $namespace namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"}[10m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total memory  usage by pods in $namespace",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(namespace) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "memory  usage by pods in $namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$node Node details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Node readiness for  $node ",
     "type": "graph",
     "description": "This panel shows the NotReady state of nodes. If any node goes in NotReady state, graph value will go from 1 to 0.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\",node=\"$node\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "node $node Memory/Disk/PID Pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",node=\"$node\"})",
       "legendFormat": "{{condition}}"
      }
     ]
    },
    {
     "title": "pod count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{node=\"$node\",pod!=\"\"}))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "besteffort pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",container=\"POD\",node=\"$node\"}))"
      }
     ]
    },
    {
     "title": "burstable pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id=~\".*.burstable.*\",node=\"$node\"}))"
      }
     ]
    },
    {
     "title": "guaranteed pods",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{container=\"POD\",id!~\".*.burstable.*\",id!~\".*.besteffort.*\",node=\"$node\"}))"
      }
     ]
    },
    {
     "title": "Pod count by namespace on $node ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (namespace)(container_memory_working_set_bytes{image!=\"\",node=\"$node\"})",
       "legendFormat": "{{namespace}}"
      },
      {}
     ]
    },
    {
     "title": "Pod startup latency ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": " histogram_quantile(0.99,\n  sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\",node=\"$node\"}[10m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\",node=\"$node\"}",
       "legendFormat": "{{node}}"
      },
      {}
     ]
    },
    {
     "title": "Node $node load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity_cpu_cores{node=\"$node\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Node $node CPU usage",
     "type": "graph",
     "description": "record: instance:node_cpu_utilisation:rate1m\nexpr: 1\n  - avg without(cpu, mode) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m]))",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "\n((sum by (instance) (instance:node_cpu_utilisation:rate1m)) + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Total CPU requests on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores{node=\"$node\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Total CPU limits on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits_cpu_cores{node=\"$node\"})",
       "legendFormat": "total limits"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Node $node memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"})",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "Total memory requests on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes{node=\"$node\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "Total Memory limits on $node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits_memory_bytes{node=\"$node\"})",
       "legendFormat": "total liimits "
      },
      {
       "expr": "kube_node_status_capacity{node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "kubelet_pleg_relist_duration_seconds_bucket",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (node,le) (rate(kubelet_pleg_relist_duration_seconds_bucket{node=\"$node\"}[10m])))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Top 5  memory guzzling pods on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",node=\"$node\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Top 5  memory guzzling pods on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",node=\"$node\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}