{
 "title": "Pod utilization metrics",
 "description": "Visualize your kubernetes costs at the pod level.",
 "tags": [
  "cost",
  "utilisation",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod))"
   },
   {
    "name": "container",
    "label": "container",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\"}) by (container)) "
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you CPU use of your application vs its requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=\"$pod\", container_name!=\"POD\"}[10m])) by (container_name)",
     "legendFormat": "{{ container_name }} (usage)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container}} (request)"
    }
   ]
  },
  {
   "title": "CPU Throttle Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_cfs_throttled_periods_total{pod!=\"\",namespace=~\"$namespace\", pod=\"$pod\"}[5m]) or vector(0)) by (pod, namespace)"
    }
   ]
  },
  {
   "title": "RAM Usage vs Requested",
   "type": "graph",
   "description": "This graph attempts to show you RAM use of your application vs its requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time (container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container_name!=\"POD\"}[1m])) by (container_name)",
     "legendFormat": "{{ container_name }} (usage)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=\"$pod\", container!=\"POD\"}) by (container)",
     "legendFormat": "{{ container }} (requested)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this pod, as a sum of its containers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[10m])) by (pod)",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[10m])) by (pod)",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk read writes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[10m])) by (pod)",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[10m])) by (pod)",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}