---
ReportDefinitions:
- reportName: CommonInbox
  summary: Common Inbox
  version: 1.0.0
  moduleName: common
  sourceColumns:
  - name: createddate
    label: reports.common.createddate
    type: epoch
    source: common
  - name: sendername
    label: reports.common.sendername
    type: string
    source: egpgr_router
  - name: natureoftask
    label: reports.common.natureoftask
    type: string
    source: common
  - name: status
    label: reports.common.status
    type: string
    source: common
  - name: details
    label: reports.common.details
    type: string
    source: common
  - name: url
    label: reports.common.url
    type: string
    source: common
  searchParams:
  - name: positionId
    label: reports.pgr.complaintcategorytype
    type: number
    source: seva
  - name: complainttype
    label: reports.pgr.complainttype
    type: number
    source: seva
  query: select * from (
        (select sub.createddate as createddate,sub.name as senderName,'Grievance' as natureoftask ,sub_a.code as status,
         'Complaint No.'|| sub.crn||' regarding '||
         (select name from egpgr_complainttype where code =sub.servicecode AND tenantid=sub.tenantid) ||' in '|| sub_a.code as details,
         replace('_url?/pgr/viewGrievance/:srn',':srn',replace(sub.crn, '/', '%2F')::character varying) as url from submission sub inner join submission_attribute sub_a on  sub.crn = sub_a.crn where
         sub_a.key in('systemStatus','status') and sub_a.code in ('REGISTERED','FORWARDED','PROCESSING','REOPENED','ONHOLD') and sub.positionid IN ($positionId) and sub.tenantid = $tenantid order by createdDate desc)
         union
         (select createddate as createddate,sendername as sendername,natureoftask as natureoftask,value as status, abstractestimate.abstractestimatenumber::character varying ||':'||comments as details,
         replace('_url?/non-framework/works/transaction/update/abstractEstimate/:id', ':id', replace(abstractestimate.abstractestimatenumber, '/', '%2F')::character varying) as url from EG_WF_STATES states JOIN
         egw_abstractestimate abstractestimate ON abstractestimate.stateid = states.id::character varying where type = 'AbstractEstimate' and owner_pos IN ($positionId)
         and states.tenantId=$tenantid and states.status<>2 order by states.createdDate desc)
         union
         (select createddate as createddate,sendername as sendername,natureoftask as natureoftask,value as status, abstractestimate.abstractestimatenumber::character varying ||':'||comments as details,
         replace('_url?/non-framework/works/transaction/update/abstractEstimate/:id', ':id', replace(abstractestimate.abstractestimatenumber, '/', '%2F')::character varying) as url from EG_WF_STATES states JOIN
         egw_abstractestimate abstractestimate ON abstractestimate.stateid = states.id::character varying where type = 'SpilloverAbstractEstimate' and owner_pos IN ($positionId)
         and states.tenantId=$tenantid and states.status<>2 order by states.createdDate desc)
         union
         (select createddate as createddate,sendername as sendername,natureoftask as natureoftask,value as status, detailedestimate.id::character varying ||':'||comments as details,
         replace('_url?/non-framework/works/transaction/viewDetailedEstimate/:id', ':id', replace(detailedestimate.estimatenumber, '/', '%2F')::character varying) as url from EG_WF_STATES states JOIN
         egw_detailedestimate detailedestimate ON detailedestimate.stateid = states.id::character varying where type = 'DetailedEstimate' and owner_pos IN ($positionId)
         and states.tenantId=$tenantid and states.status<>2 order by states.createdDate desc)
         union
         (select createddate as createddate,sendername as sendername,natureoftask as natureoftask,value as status, detailedestimate.id::character varying ||':'||comments as details,
         replace('_url?/non-framework/works/transaction/viewDetailedEstimate/:id', ':id', replace(detailedestimate.estimatenumber, '/', '%2F')::character varying) as url from EG_WF_STATES states JOIN
         egw_detailedestimate detailedestimate ON detailedestimate.stateid = states.id::character varying where type = 'SpilloverDetailedEstimate' and owner_pos IN ($positionId)
         and states.tenantId=$tenantid and states.status<>2 order by states.createdDate desc)) result
         order by createddate desc;
         
