ReportDefinitions:
- reportName: NOCApplicationReport
  summary: Report to the NOC user to show the list of application processed
  version: 1.0.0
  moduleName: rainmaker-nocsrv
  sourceColumns:
  - name: applicationno
    label: reports.noc.applicationno
    type: string
    source: noc
  - name: applicationType
    label: reports.noc.applicationType
    type: string
    source: noc
    total: false
  - name: createdTime
    label: reports.noc.createdTime
    type: long
    source: noc
    total: false
  - name: applicationStatus
    label: reports.noc.applicationStatus
    type: string
    source: noc
    total: false
  searchParams:
  - name: fromDate
    label: reports.noc.fromDate
    type: epoch
    source: noc
    isMandatory: true
    searchClause: AND createdTime >= $fromDate
  - name: toDate
    label: reports.noc.toDate
    type: epoch
    source: noc
    isMandatory: true
    searchClause: AND lastModifiedTime <= $toDate
  - name: status
    label: reports.noc.status
    type: singlevaluelist
    source: noc
    isMandatory: false
    searchClause: AND status = $status
  - name: applicationType
    label: reports.noc.applicationType
    type: singlevaluelist
    source: noc
    isMandatory: false
    searchClause: AND applicationType = $applicationType
  - name: nocType
    label: reports.noc.nocType
    type: string
    source: noc
    isMandatory: false
    searchClause: AND nocType = $nocType
  query: |
        select applicationno,applicationType,createdTime,applicationStatus,lastModifiedTime from eg_noc order by applicationno

