---
ReportDefinitions:
- reportName: ObpsDailyCollectionReport
  decryptionPathId: ObpsDailyCollectionReport
  summary: OBPS Daily Collection Report
  version: 1.0.0
  moduleName: rainmaker-obps
  sourceColumns:
  - name: receiptdate
    label: report.obps.receiptdate
    type: string
    source: obps
    total: false
  - name: receiptnumber
    label: report.obps.receiptnumber
    type: string
    source: obps
    total: false
  - name: applicationnumber
    label: report.obps.applicationnumber
    type: string
    source: obps
    total: false
  - name: applicationtype
    label: report.obps.applicationtype
    type: string
    source: obps
    total: false
  - name: name
    label: report.obps.name
    type: string
    source: obps
    total: false
  - name: instrumenttype
    label: report.obps.instrumenttype
    type: string
    source: obps
    total: false
  - name: chequedate
    label: report.obps.chequedate
    type: string
    source: obps
    total: false
  - name: chequeno
    label: report.obps.chequeno
    type: string
    source: obps
    total: false
  - name: bankname
    label: report.obps.bankname
    type: string
    source: obps
    total: false
  - name: transactionid
    label: report.obps.transactionid
    type: string
    source: obps
    total: false
  - name: lastfourdigits
    label: report.obps.lastfourdigits
    type: string
    source: obps
    total: false
  - name: totalamountpaid
    label: report.obps.totalamountpaid
    type: string
    source: obps
    total: true
  - name: instrumentstatus
    label: report.obps.instrumentstatus
    type: string
    source: obps
    total: false
  searchParams:
  - name: fromDate
    label: FromDate
    type: epoch
    source: obps
    isMandatory: true
    searchClause: AND bpa.createdtime >= $fromDate
  - name: toDate
    label: ToDate
    type: epoch
    source: obps
    isMandatory: true
    searchClause: AND bpa.createdtime  <= $toDate 
  - name: instrumentType
    label: reports.obps.instrumenttype
    type: string
    source: obps
    isMandatory: false
    searchClause: AND paymentmode = $instrumentType
  - name: instrumentStatus
    label: reports.obps.instrumentstatus
    type: string
    source: obps
    isMandatory: false
    searchClause: AND instrumentstatus = $instrumentStatus
  - name: collectionOperator
    label: CollectionOperator
    type: string
    source: obps
    isMandatory: false
    searchClause: AND egcl_payment.createdby = $collectionOperator
  query: select to_char(To_timestamp(receiptdate / 1000), 'DD/MM/YYYY') as receiptdate, receiptnumber,bpa.applicationno as applicationnumber,bp.additionaldetails->>'applicationType' as applicationtype,  eg_user.name as name, paymentmode as instrumenttype, CASE WHEN paymentmode='CHEQUE' THEN  to_char(To_timestamp(instrumentdate/ 1000), 'DD/MM/YYYY') ELSE null END as chequedate, CASE WHEN paymentmode='CHEQUE' THEN instrumentnumber ELSE null END as chequeno, egcl_payment.additionaldetails->'bankDetails'->'BANK' as bankname,  CASE WHEN paymentmode='ONLINE' THEN transactionnumber ELSE null END as transactionid ,CASE WHEN paymentmode='CARD' THEN substring(instrumentnumber,1,4) ELSE null END as lastfourdigits, totalamountpaid, instrumentstatus from egcl_payment inner join egcl_paymentdetail on egcl_payment.id=egcl_paymentdetail.paymentid inner join egcl_bill on  egcl_paymentdetail.billid=egcl_bill.id inner join eg_bpa_buildingplan bpa on consumercode=bpa.applicationno LEFT OUTER JOIN eg_land_unit land ON land.landinfoid = bpa.landid INNER JOIN eg_land_landinfo landinfo ON land.landinfoid = landinfo.id INNER JOIN eg_land_ownerinfo owner ON owner.landinfoid = landinfo.id LEFT OUTER JOIN eg_user  ON eg_user.uuid =owner.uuid where egcl_paymentdetail.businessservice='BPA.LOW_RISK_PERMIT_FEE' and bpa.tenantid= $tenantid


