serviceMaps:
  serviceName: product
  mappings:
    - version: 1.0
      description: Persists Product
      fromTopic: pg-save-product-topic
      isTransaction: true
      queryMaps:
        - query: INSERT INTO staging.product(id, tenantId, type, name, manufacturer, additionalDetails, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion, isDeleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.id
            - jsonPath: $.*.tenantId
            - jsonPath: $.*.type
            - jsonPath: $.*.name
            - jsonPath: $.*.manufacturer
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.createdBy
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.createdTime
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted

    - version: 1.0
      description: Updates Product
      fromTopic: pg-update-product-topic
      isTransaction: true
      queryMaps:
        - query: UPDATE staging.product SET tenantId = ?, type = ?, name = ?, manufacturer = ?, additionalDetails = ?, lastModifiedBy = ?, lastModifiedTime = ?, rowVersion = ?, isDeleted = ? WHERE id = ?
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.tenantId
            - jsonPath: $.*.type
            - jsonPath: $.*.name
            - jsonPath: $.*.manufacturer
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.id

    - version: 1.0
      description: Saves a product variant
      fromTopic: pg-save-product-variant-topic
      isTransaction: true
      queryMaps:
        - query: INSERT INTO staging.product_variant(id, tenantId, productId, sku, variation, additionalDetails, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion, isDeleted) VALUES (?,?,?,?,?,?,?,?,?,?,?,?);
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.id
            - jsonPath: $.*.tenantId
            - jsonPath: $.*.productId
            - jsonPath: $.*.sku
            - jsonPath: $.*.variation
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.createdBy
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.createdTime
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted

    - version: 1.0
      description: Updates a product variant
      fromTopic: pg-update-product-variant-topic
      isTransaction: true
      queryMaps:
        - query: UPDATE staging.product_variant SET tenantId = ?, productId = ?, sku = ?, variation = ?, additionalDetails = ?, lastModifiedBy = ?, lastModifiedTime = ?, rowVersion = ?, isDeleted = ? WHERE id = ?;
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.tenantId
            - jsonPath: $.*.productId
            - jsonPath: $.*.sku
            - jsonPath: $.*.variation
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.id