---
ReportDefinitions:
- reportName: PrivacyAuditReport
  decryptionPathId: PrivacyAuditReport
  summary: Privacy Audit Report
  version: 1.0.0
  moduleName: privacy
  externalService:
  - entity: $.MdmsRes.ACCESSCONTROL-ROLES.roles
    apiURL: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?moduleName=ACCESSCONTROL-ROLES&masterName=roles&tenantId=$tenantId
    keyOrder: name,code
    tableName: tbl_def_roles
  sourceColumns:
  - name: date
    label: reports.privacy.date
    type: string
    source: eg_privacy_userinfo_access_audit
  - name: time
    label: reports.privacy.time
    type: string
    source: eg_privacy_userinfo_access_audit
  - name: dataviewed
    label: reports.privacy.dataviewed
    type: stringarray
    source: eg_privacy_userinfo_access_audit
  - name: dataviewedby
    label: reports.privacy.dataviewedby
    type: string
    source: eg_privacy_userinfo_access_audit
  - name: uuid
    label: reports.hrms.uuid
    type: string
    source: eg_privacy_userinfo_access_audit
    showColumn: false
  - name: rolecodes
    label: reports.privacy.role
    type: stringarray
    source: eg_privacy_userinfo_access_audit
    isLocalisationRequired: true
    localisationPrefix: ACCESSCONTROL_ROLES_ROLES_
  searchParams:
  - name: uuid
    label: reports.privacy.uuid
    type: string
    source: eg_privacy_userinfo_access_audit
    isMandatory: true
    searchClause : AND plainaccessrequest->>'recordid'=$uuid
    showColumn: false
  - name: fromDate
    label: reports.privacy.fromDate
    type: date
    source: eg_privacy_userinfo_access_audit
    searchClause : AND accesstime>=$fromDate
    isMandatory: false
  - name: toDate
    label: reports.privacy.toDate
    type: date
    source: eg_privacy_userinfo_access_audit
    searchClause : AND accesstime<=$toDate
    isMandatory: false
  query: select to_char(To_timestamp(accesstime / 1000), 'DD/MM/YYYY') as date, to_char(To_timestamp(accesstime / 1000), 'HH12:MM AM') as time, 
   translate(plainaccessrequest->>'plainRequestFields'::TEXT,'["]','') as dataviewed, eu.name as dataviewedby, eu.uuid as uuid, 
   ARRAY_TO_STRING((SELECT ARRAY(SELECT DISTINCT er.code from eg_user eu LEFT JOIN eg_userrole_v1 eur ON eu.id=eur.user_id AND eu.tenantid=eur.user_tenantid LEFT JOIN (VALUES tbl_def_roles) AS er(name,code) ON eur.role_code=er.code WHERE eu.uuid=userid AND er.code IS NOT NULL)), ',') as rolecodes 
   from eg_privacy_userinfo_access_audit as privacy inner join eg_user as eu on eu.uuid = userid and model = 'User' and translate(plainaccessrequest->>'plainRequestFields'::TEXT,'["]','') <> ''