ReportDefinitions:
- reportName: DumpingGroundDetailReport
  summary: Dumping Ground Details report
  version: 1.0.0
  moduleName: swm
  externalService:
  - entity: $.MdmsRes.swm.DumpingGround
    apiURL:  http://egov-mdms-service:8080/egov-mdms-service/v1/_get?moduleName=swm&masterName=DumpingGround&tenantId=$tenantid
    keyOrder: code,name,tenantId,isProcessingSite
    tableName: tbl_swmdumpingground
    stateData: true
  sourceColumns:
  - name: dumpinggroundname
    label: reports.swm.dumpingground
    type: string
    source: mdms
  - name: date
    label: reports.swm.date
    type: string
    source: egswm_sourcesegregation  
  - name: wetwastecollected
    label: reports.swm.wetwaste
    type: number
    source: egswm_collectiondetails
  - name: drywastecollected
    label: reports.swm.drywaste
    type: number
    source: egswm_collectiondetails
  - name: sortdate
    label: reports.swm.date
    type: string
    source: egswm_sourcesegregation 
    showColumn: false
   
  searchParams:
  - name: dumpinggroundcode
    label: reports.swm.dumpingground
    type: singlevaluelist
    source: mdms
    isMandatory: false
    stateData: true
    wrapper: true
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?moduleName=swm&masterName=DumpingGround&tenantId=$tenantid|$.MdmsRes.swm.DumpingGround.*.code|$.MdmsRes.swm.DumpingGround.*.name
    searchClause: and ssg.dumpingground = $dumpinggroundcode
  - name: wasteprocess
    label: reports.swm.wasteprocess
    type: singlevaluelist
    pattern: 'list://false:Dump,true:Process'
    source: wastetypeprocess
    isMandatory: false
    searchClause: and dg.isProcessingSite = $wasteprocess  
  - name: wastetype
    label: reports.swm.wastetype
    type: singlevaluelist
    pattern: 'list://Wet:Wet,Dry:Dry'
    source: wastetype
    isMandatory: false    
  - name: fromDate
    label: reports.swm.datefrom
    type: epoch
    source: egswm_sourcesegregation
    isMandatory: true
  - name: toDate
    label: reports.swm.dateto
    type: epoch
    source: egswm_sourcesegregation
    isMandatory: true
  query: select dg.name as dumpinggroundname, CASE WHEN $wastetype = 'Wet' THEN sum(cd.wetwastecollected) WHEN $wastetype = 'Dry' THEN 0 ELSE sum(cd.wetwastecollected) END as wetwastecollected, CASE WHEN $wastetype = 'Wet' THEN 0 WHEN $wastetype = 'Dry' THEN sum(cd.drywastecollected) ELSE sum(cd.drywastecollected) END as drywastecollected, to_char((to_timestamp(ssg.sourcesegregationdate/1000) AT TIME ZONE 'Asia/Kolkata')::date,'dd/mm/yyyy') as date, (to_timestamp(ssg.sourcesegregationdate/1000) AT TIME ZONE 'Asia/Kolkata')::date as sortdate from egswm_collectiondetails cd, egswm_sourcesegregation ssg, (VALUES tbl_swmdumpingground) as dg (code,name,tenantId,isProcessingSite) where cd.sourcesegregation = ssg.code and cd.tenantid = $tenantid and ssg.tenantid = $tenantid  and ssg.dumpingground = dg.code and ssg.sourcesegregationdate >= $fromDate and  ssg.sourcesegregationdate <= $toDate 
  groupBy: group by date, dumpinggroundname, sortdate order by dumpinggroundname, sortdate;
  
- reportName: ExpenditureIncurredReport
  summary: Expenditure incurred on Transportation report
  version: 1.0.0
  moduleName: swm
  externalService:
  - entity: $.MdmsRes.swm.VehicleType
    apiURL:  http://egov-mdms-service:8080/egov-mdms-service/v1/_get?moduleName=swm&masterName=VehicleType&tenantId=$tenantid
    keyOrder: code,name,tenantId
    tableName: tbl_swmvehicletype
    stateData: true  
  sourceColumns:
  - name: date
    label: reports.swm.date
    type: string
    source: egswm_vehiclemaintenancedetails
  - name: vehicletype
    label: reports.swm.vehicletype
    type: string
    source: mdms
  - name: registrationnumber
    label: reports.swm.registrationnumber
    type: string
    source: egswm_vehicle
  - name: fuellingcost
    label: reports.swm.fuellingcost
    type: number
    source: egswm_vehiclefuellingdetails    
  - name: maintenancecost
    label: reports.swm.maintenancecost
    type: number
    source: egswm_vehiclemaintenancedetails
  - name: salary
    label: reports.swm.salary
    type: string
    source: employee    
  - name: totalcost
    label: reports.swm.totalcost
    type: number
    source: egswm_vehiclemaintenancedetails  
  searchParams:
  - name: vehicle
    label: reports.swm.vehicle
    type: singlevaluelistac
    source: egswm_vehicle
    isMandatory: true
    wrapper: true
    pattern: http://swm-services:8080/swm-services/vehicles/_search?tenantId=$tenantid|$..regNumber|$..regNumber
  - name: typeofvehicle
    label: reports.swm.vehicletype
    type: string
    source: egswm_vehicle
    isMandatory: false
    wrapper: true
    pattern: /swm-services/vehicles/_search?tenantId=$tenantid&regNumbers={vehicle}|$..vehicleType.name|$..vehicleType.name    
  - name: fromDate
    label: reports.swm.datefrom
    type: epoch
    source: egswm_vehiclemaintenancedetails
    isMandatory: true
  - name: toDate
    label: reports.swm.dateto
    type: epoch
    source: egswm_vehiclemaintenancedetails
    isMandatory: true
  query: select to_char(result.date,'dd/mm/yyyy') as date,COALESCE(sum(result.fuellingcost),0) as fuellingcost,COALESCE(sum(result.maintenancecost),0) as maintenancecost,COALESCE(sum(result.totalcost),0) as totalcost, result.vehicletype as vehicletype, result.registrationnumber registrationnumber,'' as salary from ((select (to_timestamp(vmd.actualmaintenancedate/1000) AT TIME ZONE 'Asia/Kolkata')::date as date,0 as fuellingcost,COALESCE(sum(vmd.costincurred),0) as maintenancecost,COALESCE(sum(vmd.costincurred),0) as totalcost, vt.name as vehicletype,vehicle.regnumber as registrationnumber from egswm_vehicle vehicle, egswm_vehiclemaintenancedetails vmd, (VALUES tbl_swmvehicletype) as vt (code,name,tenantId) where vehicle.regnumber = $vehicle and vehicle.vehicletype = vt.code and vehicle.regnumber = vmd.vehicle and vehicle.tenantid = $tenantid and vmd.tenantid = $tenantid and vmd.actualmaintenancedate >= $fromDate and  vmd.actualmaintenancedate <= $toDate group by date, vt.name, registrationnumber) UNION (select (to_timestamp(vfd.transactiondate/1000) AT TIME ZONE 'Asia/Kolkata')::date as date, COALESCE(sum(vfd.totalcostincurred),0) as fuellingcost, 0 as maintenancecost, COALESCE(sum(vfd.totalcostincurred),0) as totalcost, vt.name as vehicletype,vehicle.regnumber as registrationnumber from egswm_vehicle vehicle, egswm_vehiclefuellingdetails vfd, (VALUES tbl_swmvehicletype) as vt (code,name,tenantId) where vehicle.regnumber = $vehicle and vehicle.vehicletype = vt.code and vehicle.regnumber = vfd.vehicle and vehicle.tenantid = $tenantid and vfd.tenantid = $tenantid and vfd.transactiondate >= $fromDate and  vfd.transactiondate <= $toDate group by date, vt.name, registrationnumber)) as result group by result.date, result.registrationnumber, result.vehicletype order by result.registrationnumber, result.date, result.vehicletype;
