serviceMaps:
  serviceName: product
  mappings:
    - version: 1.0
      description: Persists Product
      fromTopic: save-product-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: PRODUCT
      objecIdJsonPath: $.Product.*.id
      tenantIdJsonPath: $.Product.*.tenantId
      userUuidJsonPath: $.RequestInfo.userInfo.uuid
      transactionCodeJsonPath: $.Product.*.id
      auditAttributeBasePath: $.Product.*
      queryMaps:
        - query: INSERT INTO health.product(id, tenantId, type, name, manufacturer, additionalDetails, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion, isDeleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.Product.*
          jsonMaps:
            - jsonPath: $.Product.*.id
            - jsonPath: $.Product.*.tenantId
            - jsonPath: $.Product.*.type
            - jsonPath: $.Product.*.name
            - jsonPath: $.Product.*.manufacturer
            - jsonPath: $.Product.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.Product.*.auditDetails.createdBy
            - jsonPath: $.Product.*.auditDetails.lastModifiedBy
            - jsonPath: $.Product.*.auditDetails.createdTime
            - jsonPath: $.Product.*.auditDetails.lastModifiedTime
            - jsonPath: $.Product.*.rowVersion
            - jsonPath: $.Product.*.isDeleted

    - version: 1.0
      description: Updates Product
      fromTopic: update-product-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: PRODUCT
      objecIdJsonPath: $.Product.*.id
      tenantIdJsonPath: $.Product.*.tenantId
      userUuidJsonPath: $.RequestInfo.userInfo.uuid
      transactionCodeJsonPath: $.Product.*.id
      auditAttributeBasePath: $.Product.*
      queryMaps:
        - query: UPDATE health.product SET tenantId = ?, type = ?, name = ?, manufacturer = ?, additionalDetails = ?, lastModifiedBy = ?, lastModifiedTime = ?, rowVersion = ?, isDeleted = ? WHERE id = ?
          basePath: $.Product.*
          jsonMaps:
            - jsonPath: $.Product.*.tenantId
            - jsonPath: $.Product.*.type
            - jsonPath: $.Product.*.name
            - jsonPath: $.Product.*.manufacturer
            - jsonPath: $.Product.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.Product.*.auditDetails.lastModifiedBy
            - jsonPath: $.Product.*.auditDetails.lastModifiedTime
            - jsonPath: $.Product.*.rowVersion
            - jsonPath: $.Product.*.isDeleted
            - jsonPath: $.Product.*.id

    - version: 1.0
      description: Saves a product variant
      fromTopic: save-product-variant-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: PRODUCT
      objecIdJsonPath: $.ProductVariant.*.id
      tenantIdJsonPath: $.ProductVariant.*.tenantId
      userUuidJsonPath: $.RequestInfo.userInfo.uuid
      transactionCodeJsonPath: $.ProductVariant.*.id
      auditAttributeBasePath: $.ProductVariant.*
      queryMaps:
        - query: INSERT INTO health.product_variant(id, tenantId, productId, sku, variation, additionalDetails, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion, isDeleted) VALUES (?,?,?,?,?,?,?,?,?,?,?,?);
          basePath: $.ProductVariant.*
          jsonMaps:
            - jsonPath: $.ProductVariant.*.id
            - jsonPath: $.ProductVariant.*.tenantId
            - jsonPath: $.ProductVariant.*.productId
            - jsonPath: $.ProductVariant.*.sku
            - jsonPath: $.ProductVariant.*.variation
            - jsonPath: $.ProductVariant.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.ProductVariant.*.auditDetails.createdBy
            - jsonPath: $.ProductVariant.*.auditDetails.lastModifiedBy
            - jsonPath: $.ProductVariant.*.auditDetails.createdTime
            - jsonPath: $.ProductVariant.*.auditDetails.lastModifiedTime
            - jsonPath: $.ProductVariant.*.rowVersion
            - jsonPath: $.ProductVariant.*.isDeleted

    - version: 1.0
      description: Updates a product variant
      fromTopic: update-product-variant-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: PRODUCT
      objecIdJsonPath: $.ProductVariant.*.id
      tenantIdJsonPath: $.ProductVariant.*.tenantId
      userUuidJsonPath: $.RequestInfo.userInfo.uuid
      transactionCodeJsonPath: $.ProductVariant.*.id
      auditAttributeBasePath: $.ProductVariant.*
      queryMaps:
        - query: UPDATE health.product_variant SET tenantId = ?, productId = ?, sku = ?, variation = ?, additionalDetails = ?, lastModifiedBy = ?, lastModifiedTime = ?, rowVersion = ?, isDeleted = ? WHERE id = ?;
          basePath: $.ProductVariant.*
          jsonMaps:
            - jsonPath: $.ProductVariant.*.tenantId
            - jsonPath: $.ProductVariant.*.productId
            - jsonPath: $.ProductVariant.*.sku
            - jsonPath: $.ProductVariant.*.variation
            - jsonPath: $.ProductVariant.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.ProductVariant.*.auditDetails.lastModifiedBy
            - jsonPath: $.ProductVariant.*.auditDetails.lastModifiedTime
            - jsonPath: $.ProductVariant.*.rowVersion
            - jsonPath: $.ProductVariant.*.isDeleted
            - jsonPath: $.ProductVariant.*.id