ServiceMaps:
  serviceName: product
  version: 1.0.0
  mappings:
    - topic: pg-save-product-variant-topic
      configKey: INDEX
      indexes:
        - name: pg-product-variant-index-v1
          type: product-variant
          id: $.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.auditDetails.createdTime
    - topic: pg-save-product-topic
      configKey: INDEX
      indexes:
        - name: pg-product-index-v1
          type: product
          id: $.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.auditDetails.createdTime
    - topic: pg-update-product-topic
      configKey: INDEX
      indexes:
        - name: pg-product-index-v1
          type: product
          id: $.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.auditDetails.createdTime
    - topic: pg-update-product-variant-topic
      configKey: INDEX
      indexes:
        - name: pg-product-variant-index-v1
          type: product-variant-update
          id: $.id
          isBulk: true
          jsonPath: $.*
          timeStampField: $.auditDetails.createdTime